name: Code Quality Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-lints-and-code-quality-checks:
    name: PR Lints and Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: validate pr title
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '^(feat|fix|docs|style|refactor|test|chore)\((frontend|backend|pipeline)\): [a-z].+$'
          title-regex-flags: 'g'
          error-message: 'Refer to the confluence page for the rules on PR titles'
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: run lints
        run: yarn lint
      - name: check prettier formatting
        run: yarn format
      - name: run tests enforcing coverage threshold
        run: yarn test:all-c
