name: Pr Lints

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-lints:
     name: Code Quality Checks
     runs-on: ubuntu-latest

     steps:
      - name: validate pr title
        uses: seferov/pr-lint-action@master
        with:
          title-regex: '^(feat|fix|style|refactor|test)\((frontend|backend|config|pipeline)\): [a-z].+$|^(docs|chore): [a-z].+$'
          title-regex-flags: 'g'
          error-message: 'Refer to the confluence page for the rules on PR titles'
